[package]
name = "genetic_ode"
version = "0.3.0"
authors = ["Garrett Tetrault"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rand_distr = "0.2.2"